name: lean

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Elan and Lean
        run: |
          curl -fL --retry 5 --retry-delay 3 \
            https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          elan default leanprover/lean4:v4.27.0

      - name: Generate lake manifest
        run: lake update

      - uses: leanprover/lean-action@v1
        with:
          auto-config: false
          build: default
          test: default
          lint: default
          mk_all-check: false
          use-mathlib-cache: false
          check-reservoir-eligibility: false
          lean4checker: false
          use-github-cache: true
          lake-package-directory: .
          reinstall-transient-toolchain: false

