name: lean

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1
        with:
          auto-config: true
          build: default
          test: default
          lint: default
          mk_all-check: false
          use-mathlib-cache: false
          check-reservoir-eligibility: false
          lean4checker: false
          use-github-cache: true
          lake-package-directory: .
          reinstall-transient-toolchain: false

